module.exports = {
  ADD_QUESTION: "ADD_QUESTION",
  REMOVE_QUESTION: "REMOVE_QUESTION",
  UPDATE_QUESTION: "UPDATE_QUESTION",
  ADD_RESPONSE: "ADD_RESPONSE",
  REMOVE_RESPONSE: "REMOVE_RESPONSE",
  UPDATE_RESPONSE: "UPDATE_RESPONSE",
  UPDATE_POLL: "UPDATE_POLL",
};
