module.exports = {
  QUESTION_FILTERS_RECEIVED: "QUESTION_FILTERS_RECEIVED",
  QUESTION_FILTER_RECEIVED: "QUESTION_FILTER_RECEIVED",
  UPDATE_QUESTION_FILTER: "UPDATE_QUESTION_FILTER",
  TOGGLE_SINGLE_CHECK: "TOGGLE_SINGLE_CHECK",
  TOGGLE_CHECKS: "TOGGLE_CHECKS",
  CHECK_ALL: "CHECK_ALL",
  CHECK_EVERYTHING: "CHECK_EVERYTHING",
  CHECK_NOTHING: "CHECK_NOTHING"
};
