json.id user.id
json.username user.username
json.email user.email
json.name user.name
json.is_guest user.is_guest
json.active_question_id user.active_question_id
json.url_suffix user.url_suffix
json.created_at user.created_at
json.updated_at user.updated_at
